#!/usr/bin/env fish
sudo nix-channel --update
and nix flake update ~/nome
and sudo nixos-rebuild switch --flake ~/nome#quartz
and set osResult success
or set osResult failure
home-manager switch --flake ~/nome#l
and set homeResult success
or set homeResult failure
sudo nix-collect-garbage
echo "
NixOS build: $osResult
   HM build: $homeResult"\n
